FROM google/cloud-sdk
ADD swarm-client-1.9-jar-with-dependencies.jar $HOME/swarm-client.jar
#CMD java -jar swarm-client.jar -master http://${JENKINS_MASTER_SERVICE_HOST}:${JENKINS_MASTER_SERVICE_PORT} -labels ${LABELS}
CMD env
